source 'http://rubygems.org'

gem 'rails', '3.2.13'

gem 'rdoc'
gem "haml"
gem "rdiscount"
gem "jquery-rails"
gem 'coffee-filter'
gem 'bootstrap-sass'

group :assets do    
  gem 'sass-rails'  
  gem 'coffee-rails'
  gem 'uglifier'    
end                 


