api: { host: 0.0.0.0, port: 8023 }
devices:
  system:
    driver: system
    primary_interface: wlan0 
  #rudder:
    ## Note that we could make the max a bit higher, but not the min. And, I want 
    ## them equidistant, to make the calculations easier:
    #driver: phidgets_advanced_servo
    #serial: 305160
    #servo_num: 0
    #max_position: 165
    #min_position: 60
  #throttle: 
    ## NOTE: The max_throttle is actually about 140+ on my model, but, I wanted to
    ## cap the speed. Also, the absolute min_velocity is 92, 91 is 'zero' throttle 
    ## and 80 is to give us a bit less sensitivity at the low end.
    #driver: phidgets_advanced_servo
    #serial: 306238
    #servo_num: 0
    #max_position: 112
    #min_position: 80
  #analogs:
    #driver: phidgets_interface_kit
    #serial: 337305,
    #interval: 0.5,
    #sensors:
      #- {type: humidity, location: Cabin}
      #- {type: temperature, location: Engine}
      #- {type: temperature, location: Cabin}
      #-
      #- {type: voltage, location: Battery 1}
      #- {type: voltage, location: Battery 2}
      #- {type: voltage, location: InterfaceKit}
      #- {type: voltage, location: MinnowBoard}
  #gps:
    #driver: phidgets_gps
    #serial: 284771 
  ##orientation:
    #driver: phidgets_spatial
    #serial: 302012
    #compass_correction: [ 0.338590, 0.227589, 0.173635, -0.077661, 2.608094, 
      #2.742003, 3.510178, -0.043266, -0.049816, -0.044693, 0.045490, -0.064236, 
      #0.057208 ]
