source 'https://rubygems.org'

gem 'rspec'
gem 'em-websocket'

gem 'vmstat'
gem 'rusage'

gem 'artoo', :path => "/home/cderose/Documents/development/artoo"
gem 'phidgets_native', :path => "/home/cderose/Documents/development/phidgets_native"
